/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlth.views.admin;

import com.qlth.model.ThucHanh;
import database.DBQuanLyThucHanh;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ADMIN
 */
public class viewBaoCaoTheoThang extends javax.swing.JFrame {

    /**
     * Creates new form viewBaoCaoTheoThang
     */
    public viewBaoCaoTheoThang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboNam = new javax.swing.JComboBox<>();
        comboThang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        buttonXuatBaoCao = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BÁO CÁO THEO THÁNG");

        jLabel2.setText("Năm: ");

        comboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026" }));

        comboThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboThang.setSelectedIndex(8);

        jLabel3.setText("Tháng: ");

        buttonXuatBaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/icons/save.png"))); // NOI18N
        buttonXuatBaoCao.setText("Xuất báo cáo ");
        buttonXuatBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXuatBaoCaoActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/icons/return.png"))); // NOI18N
        jButton2.setText("thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(66, 66, 66)
                                .addComponent(comboThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(buttonXuatBaoCao)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonXuatBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AdminScreenMain admin=new AdminScreenMain();
        admin.setLocationRelativeTo(admin);

        admin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonXuatBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXuatBaoCaoActionPerformed
        // TODO add your handling code here:
        new Thread(() -> {
            String nam = comboNam.getSelectedItem().toString();
            String thang = comboThang.getSelectedItem().toString();

            String ngayBatDau = String.format("%s-%s-01", nam, thang);
            xuatBaoCaoTheoThang(ngayBatDau, "D:/BaoCao_Nam" + nam + "_Thang" + thang + "_ThoiGianXuat_" + LocalDate.now() + ".xlsx");
        }).start();
    }//GEN-LAST:event_buttonXuatBaoCaoActionPerformed

    private void xuatBaoCaoTheoThang(String ngay, String path) {
        ArrayList<Integer> listMaPhongMay = DBQuanLyThucHanh.getListMaPhongMay();
        int rowid;
        int cellid;
        XSSFRow row;
        XSSFWorkbook workbook = new XSSFWorkbook();

        for (int tuan = 1; tuan <= 5; tuan++) {
            XSSFSheet spreadsheet = workbook.createSheet("Tuần " + tuan);
            buttonXuatBaoCao.setText(String.format("%3.2f",((float)tuan / 5)*100) + "%");
            rowid = 0;
            String ngayBatDau_ketThuc = DBQuanLyThucHanh.getThoiGianBatDauDenKetThucTuan(ngay, tuan);

            String[] splitNgay = ngayBatDau_ketThuc.split("\\|");
            String ngayBatDau = splitNgay[0];
            String ngayKetThuc = splitNgay[6];

            for (Integer integer : listMaPhongMay) {
                ArrayList<ThucHanh> danhSachDaDangKi = DBQuanLyThucHanh.getDanhSachDaDangKi(ngayBatDau, ngayKetThuc, integer);
                if (danhSachDaDangKi == null) {
                    continue;
                }

                // row 1
                row = spreadsheet.createRow(rowid++);
                cellid = 0;

                String tenPhongMay = DBQuanLyThucHanh.getTenPhongMay(integer);

                Cell cell = row.createCell(cellid++);
                cell.setCellValue(tenPhongMay);

                cell = row.createCell(cellid++);
                cell.setCellValue("Ngày");
                for (String string : splitNgay) {
                    cell = row.createCell(cellid++);
                    cell.setCellValue(string);
                }

                // row 2
                row = spreadsheet.createRow(rowid++);
                cellid = 0;
                cell = row.createCell(cellid++);
                cell.setCellValue("");
                cell = row.createCell(cellid++);
                cell.setCellValue("Ca");
                cell = row.createCell(cellid++);
                cell.setCellValue("Thứ 2");
                cell = row.createCell(cellid++);
                cell.setCellValue("Thứ 3");
                cell = row.createCell(cellid++);
                cell.setCellValue("Thứ 4");
                cell = row.createCell(cellid++);
                cell.setCellValue("Thứ 5");
                cell = row.createCell(cellid++);
                cell.setCellValue("Thứ 6");
                cell = row.createCell(cellid++);
                cell.setCellValue("Thứ 7");
                cell = row.createCell(cellid++);
                cell.setCellValue("Thứ 8 - CN");

                // row 3
                row = spreadsheet.createRow(rowid++);
                cellid = 0;
                cell = row.createCell(cellid++);
                cell.setCellValue("");
                cell = row.createCell(cellid++);
                cell.setCellValue("S");

                while (cellid < 9) {
                    ThucHanh lichInCurrentCell = isInDanhSachDaDangKi(danhSachDaDangKi, cellid - 2, "S", splitNgay);
                    cell = row.createCell(cellid++);
                    if (lichInCurrentCell != null) {
                        cell.setCellValue(String.format("%s\n%s\n%s", lichInCurrentCell.getLopHocPhan().getMaLopHocPhan(), lichInCurrentCell.getLopHocPhan().getGiangVien().getTenGiangVien(), lichInCurrentCell.getLopHocPhan().getTenMonHoc()));
                    } else {
                        cell.setCellValue("#N/A");
                    }
                }

                // row 4
                row = spreadsheet.createRow(rowid++);
                cellid = 0;

                cell = row.createCell(cellid++);
                cell.setCellValue("");
                cell = row.createCell(cellid++);
                cell.setCellValue("C");

                while (cellid < 9) {
                    ThucHanh lichInCurrentCell = isInDanhSachDaDangKi(danhSachDaDangKi, cellid - 2, "C", splitNgay);
                    cell = row.createCell(cellid++);
                    if (lichInCurrentCell != null) {
                        cell.setCellValue(String.format("%s\n%s\n%s", lichInCurrentCell.getLopHocPhan().getMaLopHocPhan(), lichInCurrentCell.getLopHocPhan().getGiangVien().getTenGiangVien(), lichInCurrentCell.getLopHocPhan().getTenMonHoc()));
                    } else {
                        cell.setCellValue("#N/A");
                    }
                }

                // row 5
                row = spreadsheet.createRow(rowid++);
                cellid = 0;
                cell = row.createCell(cellid++);
                cell.setCellValue("");
                cell = row.createCell(cellid++);
                cell.setCellValue("T");

                while (cellid < 9) {
                    ThucHanh lichInCurrentCell = isInDanhSachDaDangKi(danhSachDaDangKi, cellid - 2, "T", splitNgay);
                    cell = row.createCell(cellid++);
                    if (lichInCurrentCell != null) {
                        cell.setCellValue(String.format("%s\n%s\n%s", lichInCurrentCell.getLopHocPhan().getMaLopHocPhan(), lichInCurrentCell.getLopHocPhan().getGiangVien().getTenGiangVien(), lichInCurrentCell.getLopHocPhan().getTenMonHoc()));
                    } else {
                        cell.setCellValue("#N/A");
                    }
                }
            }
        }

        FileOutputStream out = null;
        try {
            out = new FileOutputStream(
                    new File(path));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(viewBaoCaoTheoTuan.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            workbook.write(out);
            out.close();
        } catch (IOException ex) {
            Logger.getLogger(viewBaoCaoTheoTuan.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(rootPane, """
                                                \u0110\u00e3 xu\u1ea5t b\u00e1o c\u00e1o.
                                                """ + path);
        buttonXuatBaoCao.setText("Xuất báo cáo ");
    }

    private ThucHanh isInDanhSachDaDangKi(ArrayList<ThucHanh> danhSachDaDangKi, int col, String buoiTH, String[] splitNgay) {
        String ngayTH = splitNgay[col];

        for (ThucHanh thucHanh : danhSachDaDangKi) {
//            System.out.println(thucHanh.getNgayThucHanh() + "-" + ngayTH);
            if (thucHanh.getNgayThucHanh().equalsIgnoreCase(ngayTH) && thucHanh.getTietTH().equalsIgnoreCase(buoiTH)) {
//                System.out.println("yes");
                return thucHanh;
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewBaoCaoTheoThang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewBaoCaoTheoThang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewBaoCaoTheoThang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewBaoCaoTheoThang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewBaoCaoTheoThang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonXuatBaoCao;
    private javax.swing.JComboBox<String> comboNam;
    private javax.swing.JComboBox<String> comboThang;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
