/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlth.views.admin;

import com.qlth.model.LopHocPhan;
import com.qlth.model.Phong;
import com.qlth.model.PhongMay;
import com.qlth.model.ToaNha;
import database.DBQuanLyThucHanh;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class viewManagerRoom extends javax.swing.JFrame {

    /**
     * Creates new form viewManagerRoom
     */
    public viewManagerRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        maychieu = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        maphongmay = new javax.swing.JTextField();
        somaychieu = new javax.swing.JSpinner();
        pm3 = new javax.swing.JCheckBox();
        pm1 = new javax.swing.JCheckBox();
        pm2 = new javax.swing.JCheckBox();
        pm4 = new javax.swing.JCheckBox();
        phong = new javax.swing.JComboBox<>();
        toa = new javax.swing.JComboBox<>();
        sudungduoc = new javax.swing.JRadioButton();
        baotri = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        somaytinh = new javax.swing.JSpinner();
        tenphongmay = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        themphongmay = new javax.swing.JButton();
        suaphongmay = new javax.swing.JButton();
        xoaphongmay = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        exxit = new javax.swing.JButton();
        ressetphongmay = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ PHÒNG MÁY");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel14.setText("mã phòng máy");

        jLabel15.setText("tên phòng máy");

        jLabel16.setText("địa chỉ phòng máy");

        maychieu.setText("số máy chiếu");

        jLabel18.setText("tình trạng");

        jLabel19.setText("các phần mềm sử dụng");

        maphongmay.setEditable(false);
        maphongmay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        maphongmay.setEnabled(false);

        pm3.setText("Excel 2019");
        pm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm3ActionPerformed(evt);
            }
        });

        pm1.setText("Visual Studio Code");
        pm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm1ActionPerformed(evt);
            }
        });

        pm2.setText("Word 2019");

        pm4.setText("Dream Weaver");

        buttonGroup1.add(sudungduoc);
        sudungduoc.setText("Sử dụng được");

        buttonGroup1.add(baotri);
        baotri.setText("bảo trì");

        jLabel1.setText("số máy tính");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(56, 56, 56)
                        .addComponent(maphongmay, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(maychieu)
                            .addComponent(jLabel15))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(somaychieu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(toa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tenphongmay, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pm1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pm3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(somaytinh, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pm4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pm2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(sudungduoc)
                        .addGap(72, 72, 72)
                        .addComponent(baotri)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(maphongmay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(somaytinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sudungduoc)
                        .addComponent(baotri)
                        .addComponent(jLabel18))
                    .addComponent(tenphongmay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pm1)
                    .addComponent(toa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(pm2)
                        .addComponent(phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pm3)
                        .addComponent(pm4))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maychieu)
                        .addComponent(somaychieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        themphongmay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/icons/add2.png"))); // NOI18N
        themphongmay.setText("thêm");
        themphongmay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroom(evt);
            }
        });

        suaphongmay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/icons/edit.png"))); // NOI18N
        suaphongmay.setText("sửa");
        suaphongmay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatephongmay(evt);
            }
        });

        xoaphongmay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/icons/delete.png"))); // NOI18N
        xoaphongmay.setText("xóa");
        xoaphongmay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete(evt);
            }
        });

        jLabel20.setText("tìm kiếm theo tên phòng");

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        exxit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/icons/return.png"))); // NOI18N
        exxit.setText("đóng");
        exxit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exxitActionPerformed(evt);
            }
        });

        ressetphongmay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/icons/delete.png"))); // NOI18N
        ressetphongmay.setText("reset");
        ressetphongmay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ressetphongmayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(themphongmay)
                        .addGap(66, 66, 66)
                        .addComponent(suaphongmay)))
                .addGap(72, 72, 72)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(xoaphongmay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(ressetphongmay)
                        .addGap(49, 49, 49)
                        .addComponent(exxit)
                        .addGap(33, 33, 33))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themphongmay)
                    .addComponent(suaphongmay)
                    .addComponent(xoaphongmay)
                    .addComponent(exxit)
                    .addComponent(ressetphongmay))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "stt", "mã phòng máy", "tên phòng máy", "địa chỉ phòng máy", "số máy chiếu", "số máy tính", "tình trạng", "danh sách phầ mềm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        table.setMinimumSize(new java.awt.Dimension(60, 40));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("quản lý phòng máy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(449, 449, 449))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete
        // TODO add your handling code here:
        new Thread(() -> {
            try {
                DBQuanLyThucHanh.deletePhongMay(Integer.parseInt(maphongmay.getText()));
                JOptionPane.showMessageDialog(rootPane, "xóa thành công");
                  ArrayList<PhongMay> arrPM = DBQuanLyThucHanh.getDanhSachPhongMay();
            DefaultTableModel model = (DefaultTableModel) table.getModel();

            int numberRowsOfTable = arrPM.size();
            model.setRowCount(numberRowsOfTable);

            for (int i = 0; i < numberRowsOfTable; i++) {
                model.setValueAt(i, i, 0);
                model.setValueAt(arrPM.get(i).getMaPhongMay(), i, 1);
                model.setValueAt(arrPM.get(i).getTenPhongMay(), i, 2);
                model.setValueAt(arrPM.get(i).getDiaChiPhongMay(), i, 3);
                model.setValueAt(arrPM.get(i).getSoMayChieu(), i, 4);
                model.setValueAt(arrPM.get(i).getSoMayTinh(), i, 5);
                model.setValueAt(arrPM.get(i).getTinhTrangPhong(), i, 6);
                model.setValueAt(arrPM.get(i).getDanhSachPhanMem(), i, 7);
            }
            } catch (Exception ex) {
                Logger.getLogger(viewManagerRoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();
       
    }//GEN-LAST:event_delete

    private void exxitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exxitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AdminScreenMain admin = new AdminScreenMain();
        admin.setLocationRelativeTo(admin);
        admin.setVisible(true);
    }//GEN-LAST:event_exxitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //get líst table
        new Thread(() -> {
            try {
                sudungduoc.setSelected(true);
                
                //get list combobox
                if (DBQuanLyThucHanh.getDanhSachPhong().size() != 0) {
                    DefaultComboBoxModel defaultComboBoxModel = (DefaultComboBoxModel) phong.getModel();
                    for (int p : DBQuanLyThucHanh.getDanhSachPhong()) {
                        defaultComboBoxModel.addElement(p);
                    }
                }
                if (DBQuanLyThucHanh.getDanhSachToaNha().size() != 0) {
                    DefaultComboBoxModel defaultComboBoxModel = (DefaultComboBoxModel) toa.getModel();
                    for (String toa : DBQuanLyThucHanh.getDanhSachToaNha()) {
                        defaultComboBoxModel.addElement(toa);
                    }
                }
                ArrayList<PhongMay> arrPM = DBQuanLyThucHanh.getDanhSachPhongMay();
            DefaultTableModel model = (DefaultTableModel) table.getModel();

            int numberRowsOfTable = arrPM.size();
            model.setRowCount(numberRowsOfTable);

            for (int i = 0; i < numberRowsOfTable; i++) {
                model.setValueAt(i, i, 0);
                model.setValueAt(arrPM.get(i).getMaPhongMay(), i, 1);
                model.setValueAt(arrPM.get(i).getTenPhongMay(), i, 2);
                model.setValueAt(arrPM.get(i).getDiaChiPhongMay(), i, 3);
                model.setValueAt(arrPM.get(i).getSoMayChieu(), i, 4);
                model.setValueAt(arrPM.get(i).getSoMayTinh(), i, 5);
                model.setValueAt(arrPM.get(i).getTinhTrangPhong(), i, 6);
                model.setValueAt(arrPM.get(i).getDanhSachPhanMem(), i, 7);
            }
            } catch (Exception ex) {
                Logger.getLogger(viewManagerRoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();
    }//GEN-LAST:event_formWindowOpened

    private void addroom(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroom
        // TODO add your handling code here:
        new Thread(() -> {
            try {
                String tenPM = (String) tenphongmay.getText();
                String diaChiPM = "Tòa " + String.valueOf(toa.getSelectedItem()) + " - phòng" + String.valueOf(phong.getSelectedItem());
                int soMT = (int) somaytinh.getValue();
                int soMC = (int) somaychieu.getValue();
                String tinhTrang = "";
                if (sudungduoc.isSelected()) {
                    tinhTrang = "Sử dụng được";
                }
                if (baotri.isSelected()) {
                    tinhTrang = "bảo trì";
                }
                String dsPhanMem = "";
                ArrayList<String> listpm = new ArrayList();
                if (pm1.isSelected()) {
                    listpm.add(pm1.getText());
                }
                if (pm2.isSelected()) {
                    listpm.add(pm2.getText());
                }
                if (pm3.isSelected()) {
                    listpm.add(pm3.getText());
                }
                if (pm4.isSelected()) {
                    listpm.add(pm4.getText());
                }

                dsPhanMem = listpm.stream().map((string) -> string + ", ").reduce(dsPhanMem, String::concat);

                dsPhanMem = dsPhanMem.substring(0, dsPhanMem.length() - 2);

                if (tenPM.equals("")) {
                    JOptionPane.showMessageDialog(rootPane, "vui lòng nhập đủ thông tin");
                }
                if (DBQuanLyThucHanh.insertPhongMay(tenPM, diaChiPM, soMC, soMT, tinhTrang, dsPhanMem)) {
                    JOptionPane.showMessageDialog(rootPane, "thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "chưa thêm thành công");
                }
                ArrayList<PhongMay> arrPM = DBQuanLyThucHanh.getDanhSachPhongMay();
            DefaultTableModel model = (DefaultTableModel) table.getModel();

            int numberRowsOfTable = arrPM.size();
            model.setRowCount(numberRowsOfTable);

            for (int i = 0; i < numberRowsOfTable; i++) {
                model.setValueAt(i, i, 0);
                model.setValueAt(arrPM.get(i).getMaPhongMay(), i, 1);
                model.setValueAt(arrPM.get(i).getTenPhongMay(), i, 2);
                model.setValueAt(arrPM.get(i).getDiaChiPhongMay(), i, 3);
                model.setValueAt(arrPM.get(i).getSoMayChieu(), i, 4);
                model.setValueAt(arrPM.get(i).getSoMayTinh(), i, 5);
                model.setValueAt(arrPM.get(i).getTinhTrangPhong(), i, 6);
                model.setValueAt(arrPM.get(i).getDanhSachPhanMem(), i, 7);
            }
            } catch (Exception ex) {
                Logger.getLogger(viewManagerRoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();
    }//GEN-LAST:event_addroom

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        new Thread(() -> {
        try {
            // TODO add your handling code here:
            DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
            Vector<Object> roomVector = (Vector<Object>) tableModel.getDataVector().elementAt(table.getSelectedRow());
            PhongMay phongmay = new PhongMay(Integer.parseInt(roomVector.get(1).toString()), roomVector.get(2).toString(), roomVector.get(3).toString(), Integer.parseInt(roomVector.get(4).toString()), Integer.parseInt(roomVector.get(5).toString()), roomVector.get(6).toString(), roomVector.get(7).toString());
            ToaNha toaNha = new ToaNha();
            Phong p = new Phong();
            toaNha.setToa(phongmay.getDiaChiPhongMay().split(" - ")[0].split(" ")[1]);
            p.setTenPhong(phongmay.getDiaChiPhongMay().split(" - ")[1].substring(6));
            String dspm = phongmay.getDanhSachPhanMem();

            maphongmay.setText(String.valueOf(phongmay.getMaPhongMay()));
            tenphongmay.setText(phongmay.getTenPhongMay());
            somaychieu.setValue(phongmay.getSoMayChieu());
            somaytinh.setValue(phongmay.getSoMayTinh());
            if (phongmay.getTinhTrangPhong().equals(sudungduoc.getText())) {
                sudungduoc.setSelected(true);
            } else {
                sudungduoc.setSelected(false);
            }
            pm1.setSelected(false);
            pm2.setSelected(false);
            pm3.setSelected(false);
            pm4.setSelected(false);
            String[] text = dspm.split(", ");
            for (String txt : text) {
                if (txt.trim().equals(pm1.getText().trim())) {
                    pm1.setSelected(true);
                }
                if (txt.trim().equals(pm2.getText().trim())) {
                    pm2.setSelected(true);
                }
                if (txt.trim().equals(pm3.getText().trim())) {
                    pm3.setSelected(true);
                }
                if (txt.trim().equals(pm4.getText().trim())) {
                    pm4.setSelected(true);
                }
            }
            DefaultComboBoxModel comboBoxModelBuilding = (DefaultComboBoxModel) toa.getModel();
            for (int i = 0; i < comboBoxModelBuilding.getSize(); i++) {
                String itemComboBoxSelected = (String) comboBoxModelBuilding.getElementAt(i);
                if (itemComboBoxSelected.equals(toaNha.getToa().toString())) {
                    comboBoxModelBuilding.setSelectedItem(itemComboBoxSelected);
                    //System.out.println(itemComboBoxSelected);
                }

            }
            DefaultComboBoxModel comboBoxModelRoom = (DefaultComboBoxModel) phong.getModel();
            for (int i = 0; i < comboBoxModelRoom.getSize(); i++) {
                int itemComboBoxSelected = (int) comboBoxModelRoom.getElementAt(i);
                if (itemComboBoxSelected == Integer.parseInt(p.getTenPhong())) {
                    comboBoxModelRoom.setSelectedItem(itemComboBoxSelected);
                    //System.out.println(itemComboBoxSelected);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(viewManagerRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
        }).start();
    }//GEN-LAST:event_tableMouseClicked

    private void pm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pm1ActionPerformed

    private void pm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pm3ActionPerformed

    private void updatephongmay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatephongmay
        // TODO add your handling code here:
        new Thread(() -> {
        try {
            String tenPM = (String) tenphongmay.getText();
            String diaChiPM = "Tòa " + String.valueOf(toa.getSelectedItem()) + " - phòng" + String.valueOf(phong.getSelectedItem());
            int soMT = (int) somaytinh.getValue();
            int soMC = (int) somaychieu.getValue();
            String tinhTrang = "";
            if (sudungduoc.isSelected()) {
                tinhTrang = "Sử dụng được";
            }
            if (baotri.isSelected()) {
                tinhTrang = "bảo trì";
            }
            String dsPhanMem = "";
            ArrayList<String> listpm = new ArrayList();
            if (pm1.isSelected()) {
                listpm.add(pm1.getText());
            }
            if (pm2.isSelected()) {
                listpm.add(pm2.getText());
            }
            if (pm3.isSelected()) {
                listpm.add(pm3.getText());
            }
            if (pm4.isSelected()) {
                listpm.add(pm4.getText());
            }

            dsPhanMem = listpm.stream().map((string) -> string + ", ").reduce(dsPhanMem, String::concat);

            dsPhanMem = dsPhanMem.substring(0, dsPhanMem.length() - 2);
            DBQuanLyThucHanh.updatePhongMay(Integer.parseInt(maphongmay.getText()), tenPM, diaChiPM, soMC, soMT, tinhTrang, dsPhanMem);
            JOptionPane.showMessageDialog(rootPane, "sửa thành công");
             ArrayList<PhongMay> arrPM = DBQuanLyThucHanh.getDanhSachPhongMay();
            DefaultTableModel model = (DefaultTableModel) table.getModel();

            int numberRowsOfTable = arrPM.size();
            model.setRowCount(numberRowsOfTable);

            for (int i = 0; i < numberRowsOfTable; i++) {
                model.setValueAt(i, i, 0);
                model.setValueAt(arrPM.get(i).getMaPhongMay(), i, 1);
                model.setValueAt(arrPM.get(i).getTenPhongMay(), i, 2);
                model.setValueAt(arrPM.get(i).getDiaChiPhongMay(), i, 3);
                model.setValueAt(arrPM.get(i).getSoMayChieu(), i, 4);
                model.setValueAt(arrPM.get(i).getSoMayTinh(), i, 5);
                model.setValueAt(arrPM.get(i).getTinhTrangPhong(), i, 6);
                model.setValueAt(arrPM.get(i).getDanhSachPhanMem(), i, 7);
            }
        } catch (Exception ex) {
            Logger.getLogger(viewManagerRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
        }).start();
    }//GEN-LAST:event_updatephongmay

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:e
        new Thread(() -> {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String keySearch = search.getText().trim();
            if (keySearch.compareTo("") == 0) {
                JOptionPane.showMessageDialog(rootPane, "vui lòng nhập từ khóa muốn tìm kiếm");
            }
            try {
                  ArrayList<PhongMay> arrPM = DBQuanLyThucHanh.searchPhongMay(search.getText());
            DefaultTableModel model = (DefaultTableModel) table.getModel();

            int numberRowsOfTable = arrPM.size();
            model.setRowCount(numberRowsOfTable);

            for (int i = 0; i < numberRowsOfTable; i++) {
                model.setValueAt(i, i, 0);
                model.setValueAt(arrPM.get(i).getMaPhongMay(), i, 1);
                model.setValueAt(arrPM.get(i).getTenPhongMay(), i, 2);
                model.setValueAt(arrPM.get(i).getDiaChiPhongMay(), i, 3);
                model.setValueAt(arrPM.get(i).getSoMayChieu(), i, 4);
                model.setValueAt(arrPM.get(i).getSoMayTinh(), i, 5);
                model.setValueAt(arrPM.get(i).getTinhTrangPhong(), i, 6);
                model.setValueAt(arrPM.get(i).getDanhSachPhanMem(), i, 7);
            }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        }).start();
    }//GEN-LAST:event_searchKeyPressed

    private void ressetphongmayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ressetphongmayActionPerformed
        // TODO add your handling code here:
        resetform();
    }//GEN-LAST:event_ressetphongmayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                viewManagerRoom room = new viewManagerRoom();
                room.setLocationRelativeTo(room);
                room.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton baotri;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exxit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField maphongmay;
    private javax.swing.JLabel maychieu;
    private javax.swing.JComboBox<String> phong;
    private javax.swing.JCheckBox pm1;
    private javax.swing.JCheckBox pm2;
    private javax.swing.JCheckBox pm3;
    private javax.swing.JCheckBox pm4;
    private javax.swing.JButton ressetphongmay;
    private javax.swing.JTextField search;
    private javax.swing.JSpinner somaychieu;
    private javax.swing.JSpinner somaytinh;
    private javax.swing.JButton suaphongmay;
    private javax.swing.JRadioButton sudungduoc;
    private javax.swing.JTable table;
    private javax.swing.JTextField tenphongmay;
    private javax.swing.JButton themphongmay;
    private javax.swing.JComboBox<String> toa;
    private javax.swing.JButton xoaphongmay;
    // End of variables declaration//GEN-END:variables

    private void resetform() {
        maphongmay.setRequestFocusEnabled(true);
        maphongmay.setText("");
        tenphongmay.setText("");
        toa.setSelectedIndex(0);
        phong.setSelectedIndex(0);
        somaychieu.setValue(0);
        somaytinh.setValue(0);
        sudungduoc.setSelected(true);
        pm1.setSelected(false);
        pm2.setSelected(false);
        pm3.setSelected(false);
        pm4.setSelected(false);
    }
}
